# Generated by Django 5.2.6 on 2025-10-10 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAssociation',
            fields=[
                ('association_id', models.AutoField(primary_key=True, serialize=False)),
                ('confidence', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('support', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'item_associations',
                'ordering': ['-confidence'],
            },
        ),
        migrations.CreateModel(
            name='PopularitySnapshot',
            fields=[
                ('snapshot_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('order_count', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('date_recorded', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'popularity_snapshots',
                'ordering': ['-date_recorded', 'rank'],
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='last_ordered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='order_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='seasonal_boost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['last_ordered'], name='menu_items_last_or_f309a8_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['order_count'], name='menu_items_order_c_000ab4_idx'),
        ),
        migrations.AddField(
            model_name='itemassociation',
            name='source_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_items', to='api.menuitem'),
        ),
        migrations.AddField(
            model_name='itemassociation',
            name='target_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reverse_associations', to='api.menuitem'),
        ),
        migrations.AddField(
            model_name='popularitysnapshot',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popularity_snapshots', to='api.menuitem'),
        ),
        migrations.AddIndex(
            model_name='itemassociation',
            index=models.Index(fields=['source_item', 'confidence'], name='item_associ_source__402935_idx'),
        ),
        migrations.AddIndex(
            model_name='itemassociation',
            index=models.Index(fields=['target_item', 'confidence'], name='item_associ_target__01e60a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemassociation',
            unique_together={('source_item', 'target_item')},
        ),
        migrations.AddIndex(
            model_name='popularitysnapshot',
            index=models.Index(fields=['date_recorded', 'rank'], name='popularity__date_re_0e76b7_idx'),
        ),
        migrations.AddIndex(
            model_name='popularitysnapshot',
            index=models.Index(fields=['menu_item', 'date_recorded'], name='popularity__menu_it_d57d3a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='popularitysnapshot',
            unique_together={('menu_item', 'date_recorded')},
        ),
    ]
