# Generated by Django 5.2.6 on 2025-10-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_restaurant_allow_same_day_reservations_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='restaurant',
            name='restaurants_status_7a5ebb_idx',
        ),
        migrations.RemoveIndex(
            model_name='restaurant',
            name='restaurants_overall_e961a0_idx',
        ),
        migrations.RemoveIndex(
            model_name='restaurant',
            name='restaurants_is_feat_a07c01_idx',
        ),
        migrations.RemoveIndex(
            model_name='restaurant',
            name='restaurants_reserva_aef3d2_idx',
        ),
        migrations.RemoveIndex(
            model_name='specialoffer',
            name='special_off_is_acti_9a2aad_idx',
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['status', 'is_featured'], name='restaurants_status_3712e4_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['overall_rating', 'total_reviews'], name='restaurants_overall_aecf58_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['created_at'], name='restaurants_created_d66452_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['reservation_enabled', 'status'], name='restaurants_reserva_77487e_idx'),
        ),
        migrations.AddIndex(
            model_name='specialoffer',
            index=models.Index(fields=['is_active', 'is_featured'], name='special_off_is_acti_fe5b6b_idx'),
        ),
    ]
