# Generated by Django 5.2.6 on 2025-10-18 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_kitchenstation_orderitempreparation_posconnection_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantstaff',
            name='branch_access',
            field=models.ManyToManyField(blank=True, related_name='authorized_staff', to='api.branch'),
        ),
        migrations.AddField(
            model_name='restaurantstaff',
            name='can_manage_finances',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurantstaff',
            name='can_manage_reservations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurantstaff',
            name='permission_level',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('kitchen', 'Kitchen Staff'), ('delivery', 'Delivery Staff'), ('cashier', 'Cashier')], default='cashier', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='is_restaurant_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='restaurantstaff',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('chef', 'Chef'), ('cashier', 'Cashier'), ('waiter', 'Waiter'), ('delivery', 'Delivery Driver'), ('other', 'Other Staff')], max_length=20),
        ),
        migrations.CreateModel(
            name='RestaurantOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary_owner', models.BooleanField(default=False)),
                ('ownership_percentage', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'restaurant_ownership',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='owned_restaurants',
            field=models.ManyToManyField(blank=True, related_name='owners', through='api.RestaurantOwnership', to='api.restaurant'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_restaurant_owner'], name='users_is_rest_239e05_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='restaurantownership',
            unique_together={('user', 'restaurant')},
        ),
    ]
