# Generated by Django 5.2.6 on 2025-11-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_restaurantstaff_branch_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending_restaurant_name',
            field=models.CharField(blank=True, help_text='Restaurant name provided during registration for pending setup', max_length=255, null=True),
        ),
    ]
