# Generated by Django 5.2.6 on 2025-11-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_pending_restaurant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='name',
            field=models.CharField(default='Main Branch', max_length=255),
        ),
    ]
