# Generated by Django 5.2.6 on 2025-12-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_branch_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(help_text='FontAwesome or custom icon class', max_length=50)),
                ('color', models.CharField(default='#FF6B35', max_length=7)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('search_query', models.CharField(help_text='Search query to use when clicked', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'popular categories',
                'db_table': 'popular_categories',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
