# Generated by Django 5.2.6 on 2025-12-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_popularcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularcategory',
            name='restaurants',
            field=models.ManyToManyField(blank=True, related_name='popular_categories', to='api.restaurant'),
        ),
    ]
